version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - path: .env
        required: true
    depends_on:
      - server_db

  server_db:
    image: postgres
    container_name: server_database
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
